version: '3.8'
services:
  spark-jupyter:
    build: .
    container_name: spark-jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./spark-warehouse:/opt/spark-warehouse
      - "${SERVICE_ACC_PATH}:/service_acc.json"   # Mount GCS key
    restart: unless-stopped